### ISSUE TITLE
spline_example.py shown in the documentation is not working, cannot find the spline_interpolate 

### ISSUE THREAD

**Issue by yuzhangx** [LatticeQCD/AnalysisToolbox#17]

**Comment by clarkedavida** [comment]
I'll fix this right now, sorry for the incredibly later response.

**Comment by clarkedavida** [comment]
OK the documentation is fixed as of 026a0440f509275d3a15ed16c92ef51060f5e974.

This `spline_interpolate` stuff is from the original version of the AnalysisToolbox. I have never really understood how to use it, and didn't want to learn. I also found it strange/silly that it required one to compile come `C` code to work, especially since `scipy.interpolate` should have all the tools that are needed.

What exists now is rather basic. There is a `getSpline` method which is a wrapper for `LSQUnivariateSpline`. It does things like figures out some knots automatically. You can control the knots yourself if you really want to using `fixedknots`. I haven't yet tried to implement a constrained spline, if that is what you were looking for. I would like to eventually, but there is no timeline for that...

Does this help yuzhang? If I don't hear back in a week or so, I will close this thread.

Thanks for pointing the issue out. The documentation in AnalysisToolbox is unfortunately quite terrible, since I'm more or less the only person who writes it.

**Comment by clarkedavida** [comment]
I haven't heard any more feedback so I'm closing this issue.
